#!/usr/bin/env python
# coding: utf-8

# In[1]:


import numpy as np
import pandas as pd


# In[2]:


df= pd.read_csv("Data.csv")


# In[3]:


df


# In[6]:


print(df.shape)


# In[7]:


print(df.columns)


# In[8]:


print(df.info())


# In[9]:


df.describe()


# In[10]:


df["gender"]


# In[11]:


df["gender"].value_counts()


# In[23]:


df.sort_values(by= "TotalCharges", ascending= False).head(10)


# In[ ]:




